apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
  namespace: web-app
  labels:
    app: shop-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: shop-app
  template:
    metadata:
      labels:
        app: shop-app
    spec:
      containers:
        - name: shop-container
          image: shop:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  namespace: web-app
  labels:
    app: cart-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cart-app
  template:
    metadata:
      labels:
        app: cart-app
    spec:
      containers:
        - name: cart-container
          image: cart:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-deployment
  namespace: web-app
  labels:
    app: checkout-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: checkout-app
  template:
    metadata:
      labels:
        app: checkout-app
    spec:
      containers:
        - name: checkout-container
          image: checkout:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: web-app
  labels:
    app: payment-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: payment-app
  template:
    metadata:
      labels:
        app: payment-app
    spec:
      containers:
        - name: payment-container
          image: payment:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
