apiVersion: v1
kind: Service
metadata:
  name: shop-service
  namespace: web-app
spec:
  type: NodePort
  selector:
    app: shop-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001

---

apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: web-app
spec:
  type: NodePort
  selector:
    app: cart-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002

---

apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  namespace: web-app
spec:
  type: NodePort
  selector:
    app: checkout-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: web-app
spec:
  type: NodePort
  selector:
    app: payment-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
